"""
Replot diagnostic figures from the saved joint-MVN synthetic-profile .npz
without re-running the full generator.

Outputs:

PCA-mode figures (3x1, IEEE single column 3.25"):
    opt1_raw_pcs        — raw unit-norm modes v_k(z)
    opt2_sigma_weighted — sigma_k * v_k(z)   (recommended for the paper)
    opt3_log_frac_pert  — exp(sigma_k * v_k) - 1

In-situ vs synthetic comparison (2x3, IEEE double column 7.16"):
    (a) per-level r_e envelope        (b) per-level LWC envelope
    (c) cloud thickness distribution  (d) cloud optical depth tau_c
    (e) liquid water path             (f) vertical-mean alpha
                                          (with nu_eff = 1/(alpha + 3))

The PCA-mode figures only need the .npz. The comparison figure also needs
the in-situ training set: the script reads the .mat files in MAT_DIR on
first run, applies the same filters as 06_synthetic_profile_generator.py,
and caches the diagnostic arrays to in_situ_diagnostic_cache.npz so future
runs skip the .mat read.

Synthetic per-level profiles for the envelope panels are regenerated by
drawing 2000 samples from the saved joint MVN (seed=0, matching the
generator's RANDOM_SEED) and inverting the PCA — deterministic given the
saved parameters.
"""

import numpy as np
import scipy.io
import matplotlib.pyplot as plt
from matplotlib.ticker import FixedLocator, FixedFormatter, NullFormatter
from pathlib import Path


# ── Constants matching 06_synthetic_profile_generator.py ──────────────────
LWC_EPS    = 1e-3
VAR_TARGET = 0.99
TAU_C_MIN  = 3.0
DIAG_SEED  = 0          # matches RANDOM_SEED in the generator

FIGURE_DPI         = 500
FIG_WIDTH_IN_1COL  = 3.25     # IEEE single column
FIG_HEIGHT_IN_1COL = 8.5
FIG_WIDTH_IN_2COL  = 7.0      # IEEE double column (max width)
FIG_HEIGHT_IN_2COL = 5.6

NPZ_PATH = Path(
    '/Users/andrewbuggee/Documents/VS_CODE/Python-Research/lasp-CU-paper-3/'
    'synthetic_profiles/synthetic_profiles_jointMVN_N300001_L7.npz'
)
OUT_DIR    = NPZ_PATH.parent
CACHE_PATH = OUT_DIR / 'in_situ_diagnostic_cache.npz'
MAT_DIR    = Path('/Volumes/My Passport/neural_network_training_data/'
                  'saz0_allProfiles/')


# ── Visualization-option enums (PCA-modes figures) ────────────────────────
OPTION_TAG = {
    1: 'raw_pcs',
    2: 'sigma_weighted',
    3: 'log_frac_pert',
}
OPTION_XLABEL = {
    1: r'$v_k(z)$',
    2: r'$\sigma_k\,v_k(z)$',
    3: r'$\exp(\sigma_k v_k) - 1$',
}
OPTION_TITLE_SUFFIX = {
    1: 'unit-norm modes',
    2: r'$\sigma$-weighted',
    3: 'log-space frac. pert.',
}


# ── Style ─────────────────────────────────────────────────────────────────
def setup_style():
    """Compact serif style sized for 3.25" IEEE single column.

    The 2x3 comparison figure (7.16" wide) shares these sizes; per-panel
    width there is ~2.4" and the legends are dropped to fontsize 6.
    """
    plt.rcParams.update({
        'font.family':       'serif',
        'font.serif':        ['DejaVu Serif', 'Computer Modern Roman',
                              'Times New Roman'],
        'mathtext.fontset':  'cm',
        'mathtext.rm':       'serif',
        'axes.labelsize':    9,
        'axes.titlesize':    9.5,
        'figure.titlesize':  10,
        'legend.fontsize':   6.5,
        'xtick.labelsize':   8,
        'ytick.labelsize':   8,
        'axes.linewidth':    0.6,
        'lines.linewidth':   1.2,
    })


def add_panel_label(ax, label, x=0.03, y=0.96,
                    fontweight='bold', pad=1.5):
    """Panel label inside the axes upper-left corner.

    Defaults match the PCA-modes figures (bold, slightly inset). The
    comparison figure overrides to a non-bold, top-flush label so it sits
    out of the way of histogram bars that often peak near the y-axis.
    """
    ax.text(x, y, label, transform=ax.transAxes,
            fontsize=10, fontweight=fontweight, va='top', ha='left',
            bbox=dict(facecolor='white', edgecolor='none', alpha=0.75,
                      pad=pad))


# ── Helpers copied from 06_synthetic_profile_generator.py ────────────────
def project_to_common_grid(values_top_to_base, z_top_to_base, L):
    """Resample (values, z) onto a length-L grid with u=0 at base, u=1 at top."""
    z_top, z_base = float(z_top_to_base[0]), float(z_top_to_base[-1])
    if z_top == z_base:
        return np.full(L, np.mean(values_top_to_base))
    u_raw = (np.asarray(z_top_to_base) - z_base) / (z_top - z_base)
    order = np.argsort(u_raw)
    u_target = np.linspace(0.0, 1.0, L)
    return np.interp(u_target, u_raw[order],
                     np.asarray(values_top_to_base)[order])


def trapz_vertical_mean(values_top_to_base, z_top_to_base):
    v = np.asarray(values_top_to_base)
    z = np.asarray(z_top_to_base)
    integral  = abs(np.trapezoid(v, z))
    thickness = abs(z[0] - z[-1])
    return integral / thickness if thickness > 0 else float(np.mean(v))


def compute_lwp_g_per_m2(lwc_top_to_base, z_top_to_base):
    """LWP (g/m²) from LWC (g/m³) on z (km). 1000 = km → m."""
    return 1000.0 * abs(np.trapezoid(lwc_top_to_base, z_top_to_base))


def load_era5_fields(d):
    """Used only as a filter — match the generator's training-set selection."""
    if 'era5' not in d:
        return None
    try:
        dp = d['era5'].item()[6].item()
        T   = np.asarray(dp[1], dtype=np.float64)
        P   = np.asarray(dp[2], dtype=np.float64)
        vap = np.asarray(dp[4], dtype=np.float64)
    except (IndexError, AttributeError, ValueError):
        return None
    if not (len(T) == len(P) == len(vap)):
        return None
    return T, vap, P


def load_in_situ(L_common, use_cache=True):
    """Load + filter in-situ profiles, return diagnostic arrays.

    Mirrors 06_synthetic_profile_generator.py: requires re/lwc/z/tau and a
    valid era5 block, drops profiles with tau_c < TAU_C_MIN, drops duplicate
    fingerprints. Caches to CACHE_PATH so subsequent runs skip the .mat read.
    Re-loads from .mat if the cache was built at a different L_common.
    """
    if use_cache and CACHE_PATH.exists():
        cache = np.load(CACHE_PATH)
        if int(cache['L_common']) == L_common:
            return {k: cache[k] for k in cache.files}

    if not MAT_DIR.exists():
        raise FileNotFoundError(
            f'In-situ .mat directory {MAT_DIR} not mounted, and no usable '
            f'cache at {CACHE_PATH}. Mount the source drive and re-run.'
        )

    mat_files = sorted(f for f in MAT_DIR.glob('*.mat')
                       if not f.name.startswith('._'))
    print(f'Loading in-situ profiles from {len(mat_files)} .mat files...')

    re_common, lwc_common = [], []
    thickness, tau_c, lwp, alpha = [], [], [], []
    seen = set()

    for path in mat_files:
        d = scipy.io.loadmat(path, squeeze_me=True)
        if not {'re', 'z', 'tau', 'lwc'}.issubset(d.keys()):
            continue
        if load_era5_fields(d) is None:
            continue

        re_p  = np.asarray(d['re'][()],  dtype=np.float64)
        lwc_p = np.asarray(d['lwc'][()], dtype=np.float64)
        z_p   = np.asarray(d['z'][()],   dtype=np.float64)
        tau_p = float(np.asarray(d['tau'][()]).max())
        if tau_p < TAU_C_MIN:
            continue
        fp = tuple(np.round(re_p[:5], 4))
        if fp in seen:
            continue
        seen.add(fp)

        has_alpha = 'alpha_param' in d.keys()
        if has_alpha:
            a_p = np.asarray(d['alpha_param'][()], dtype=np.float64)
            n   = min(len(re_p), len(lwc_p), len(z_p), len(a_p))
            a_p = a_p[:n]
        else:
            n = min(len(re_p), len(lwc_p), len(z_p))
        re_p, lwc_p, z_p = re_p[:n], lwc_p[:n], z_p[:n]

        re_common.append(project_to_common_grid(re_p,  z_p, L_common))
        lwc_common.append(project_to_common_grid(lwc_p, z_p, L_common))
        thickness.append(abs(float(z_p[0]) - float(z_p[-1])))
        tau_c.append(tau_p)
        lwp.append(compute_lwp_g_per_m2(lwc_p, z_p))
        alpha.append(trapz_vertical_mean(a_p, z_p) if has_alpha else np.nan)

    out = {
        're_common':  np.asarray(re_common,  dtype=np.float32),
        'lwc_common': np.asarray(lwc_common, dtype=np.float32),
        'thickness':  np.asarray(thickness,  dtype=np.float32),
        'tau_c':      np.asarray(tau_c,      dtype=np.float32),
        'lwp':        np.asarray(lwp,        dtype=np.float32),
        'alpha':      np.asarray(alpha,      dtype=np.float32),
        'L_common':   np.int32(L_common),
    }
    np.savez_compressed(CACHE_PATH, **out)
    print(f'Cached in-situ diagnostic data ({len(re_common)} profiles) '
          f'-> {CACHE_PATH}')
    return out


# ── PCA-mode panel helpers ────────────────────────────────────────────────
def mode_curve(comp_k, sigma_k, option):
    if option == 1:
        return comp_k
    if option == 2:
        return sigma_k * comp_k
    if option == 3:
        return np.exp(sigma_k * comp_k) - 1.0
    raise ValueError(f'unknown option {option}')


def plot_modes_panel(ax, u, comps, score_std, var_ratio, K_show, option,
                     title):
    for k in range(K_show):
        curve = mode_curve(comps[k], score_std[k], option)
        var_pct = 100.0 * var_ratio[k]
        ax.plot(curve, u, label=fr'PC{k + 1} ({var_pct:.0f}%)')
    ax.axvline(0.0, color='0.65', linewidth=0.5)
    ax.set_ylabel('Normalized altitude')
    ax.set_xlabel(OPTION_XLABEL[option])
    ax.set_title(title)
    ax.set_ylim(0.0, 1.0)
    ax.legend(loc='center left', bbox_to_anchor=(0.94, 0.5),
              ncol=1, frameon=True, framealpha=0.9,
              handlelength=0.9, labelspacing=0.22,
              handletextpad=0.3, borderaxespad=0.0,
              fontsize=6.5)
    ax.grid(alpha=0.3)


def make_pca_modes_figure(d, option):
    mu_re      = d['pca_re_mean']
    comps_re   = d['pca_re_components']
    var_re     = d['pca_re_var_ratio']
    mu_lwc     = d['pca_lwc_mean']
    comps_lwc  = d['pca_lwc_components']
    var_lwc    = d['pca_lwc_var_ratio']
    mvn_cov    = d['mvn_cov']
    K_re       = int(d['K_re'])
    K_lwc      = int(d['K_lwc'])
    L_COMMON   = int(d['L_COMMON'])

    score_std_re  = np.sqrt(np.diag(mvn_cov)[0:K_re])
    score_std_lwc = np.sqrt(np.diag(mvn_cov)[K_re:K_re + K_lwc])

    u = np.linspace(0.0, 1.0, L_COMMON)

    fig = plt.figure(figsize=(FIG_WIDTH_IN_1COL, FIG_HEIGHT_IN_1COL))
    gs = fig.add_gridspec(
        3, 1,
        left=0.17, right=0.89, top=0.965, bottom=0.055, hspace=0.42,
    )
    axes = [fig.add_subplot(gs[i, 0]) for i in range(3)]

    # (a) Scree
    ax = axes[0]
    ax.plot(np.arange(1, len(var_re) + 1),  np.cumsum(var_re),  'o-',
            color='steelblue', markersize=3,
            label=fr'log $r_e$ (kept K={K_re})')
    ax.plot(np.arange(1, len(var_lwc) + 1), np.cumsum(var_lwc), 's-',
            color='darkorange', markersize=3,
            label=f'log LWC (kept K={K_lwc})')
    ax.axhline(VAR_TARGET, color='0.5', linestyle=':', linewidth=0.8)
    ax.set_xlabel('Principal component')
    ax.set_ylabel('Cumulative variance')
    ax.set_title('PCA scree (log-space)')
    ax.set_xlim(0, max(K_re, K_lwc) + 5)
    ax.set_ylim(0.0, 1.01)
    ax.legend(loc='lower right', frameon=True, framealpha=0.9,
              handlelength=1.4, labelspacing=0.3, fontsize=7)
    ax.grid(alpha=0.3)
    add_panel_label(ax, '(a)')

    # (b) r_e modes
    plot_modes_panel(
        axes[1], u, comps_re, score_std_re, var_re,
        K_show=K_re, option=option,
        title=fr'Log-$r_e$ modes ({OPTION_TITLE_SUFFIX[option]})',
    )
    add_panel_label(axes[1], '(b)')

    # (c) LWC modes
    plot_modes_panel(
        axes[2], u, comps_lwc, score_std_lwc, var_lwc,
        K_show=K_lwc, option=option,
        title=f'Log-LWC modes ({OPTION_TITLE_SUFFIX[option]})',
    )
    add_panel_label(axes[2], '(c)')

    return fig


# ── Comparison figure (2x3 in-situ vs synthetic) ──────────────────────────
def regenerate_diagnostic_synthetic_grid(d, n_diag=2000):
    """Reproduce the generator's diagnostic batch on the common grid.

    Same procedure as 06_synthetic_profile_generator.py: draw n_diag samples
    from the saved joint MVN, inverse-PCA the r_e and LWC score blocks,
    exp() back to physical units, subtract LWC_EPS for LWC. Deterministic
    with DIAG_SEED=0.
    """
    mu_f      = d['mvn_mean']
    cov_f     = d['mvn_cov']
    mu_re     = d['pca_re_mean']
    mu_lwc    = d['pca_lwc_mean']
    comps_re  = d['pca_re_components']                # (K_re,  L_common)
    comps_lwc = d['pca_lwc_components']               # (K_lwc, L_common)
    K_re      = int(d['K_re'])
    K_lwc     = int(d['K_lwc'])

    rng = np.random.default_rng(DIAG_SEED)
    samples = rng.multivariate_normal(mu_f, cov_f, size=n_diag)   # (n_diag, F)
    diag_re  = np.exp(mu_re  + samples[:, 0:K_re]            @ comps_re)
    diag_lwc = (np.exp(mu_lwc + samples[:, K_re:K_re + K_lwc] @ comps_lwc)
                - LWC_EPS)
    np.clip(diag_lwc, 0.0, None, out=diag_lwc)
    return diag_re, diag_lwc


def make_comparison_figure(d, in_situ):
    """2x3 in-situ vs synthetic diagnostic.

    Top row : per-level r_e envelope, per-level LWC envelope, cloud thickness.
    Bottom  : tau_c, LWP, mean alpha (with nu_eff conversion in the label).
    """
    L_COMMON = int(d['L_COMMON'])
    u   = np.linspace(0.0, 1.0, L_COMMON)
    pct = (5, 50, 95)
    # Okabe-Ito palette (Wong 2011, Nat. Methods): vermillion + blue.
    # CVD-safe for deuteranopia, protanopia, and tritanopia.
    color_in, color_syn = '#D55E00', '#0072B2'

    diag_re, diag_lwc = regenerate_diagnostic_synthetic_grid(d, n_diag=2000)

    syn_thickness = d['thickness']
    syn_tau_c     = d['tau_c']
    syn_lwp       = d['LWP_g_per_m2']
    syn_alpha     = d['mean_alpha']

    re_common    = in_situ['re_common']
    lwc_common   = in_situ['lwc_common']
    in_thickness = in_situ['thickness']
    in_tau_c     = in_situ['tau_c']
    in_lwp       = in_situ['lwp']
    in_alpha     = in_situ['alpha'][~np.isnan(in_situ['alpha'])]

    fig, axes = plt.subplots(2, 3,
                             figsize=(FIG_WIDTH_IN_2COL, FIG_HEIGHT_IN_2COL),
                             constrained_layout=True)

    # (a) per-level r_e envelope
    ax = axes[0, 0]
    p_in = np.percentile(re_common, pct, axis=0)
    p_sy = np.percentile(diag_re,   pct, axis=0)
    ax.fill_betweenx(u, p_in[0], p_in[2], alpha=0.30,
                     color=color_in, label='In-situ 5–95%')
    ax.plot(p_in[1], u, color=color_in, linewidth=1.5,
            label='In-situ median')
    ax.fill_betweenx(u, p_sy[0], p_sy[2], alpha=0.25,
                     color=color_syn, label='Synthetic 5–95%')
    ax.plot(p_sy[1], u, color=color_syn, linewidth=1.5,
            label='Synthetic median')
    ax.set_xscale('log')
    # Extend the left x-limit so the center-left legend sits in empty space
    # to the left of the envelope rather than on top of its 5th-percentile fill.
    ax.set_xlim(left=2.0)
    # Sub-decade range forces matplotlib to label many minor log ticks (2x10^0,
    # 3x10^0, ...) which crowd the narrow panel; pin to clean integer labels.
    ax.xaxis.set_major_locator(FixedLocator([2, 3, 5, 10, 20]))
    ax.xaxis.set_major_formatter(FixedFormatter(['2', '3', '5', '10', '20']))
    ax.xaxis.set_minor_formatter(NullFormatter())
    ax.set_xlabel(r'$r_e$ ($\mu$m, log)')
    ax.set_ylabel('Normalized altitude')
    ax.set_title(r'Per-level $r_e$ envelope')
    ax.legend(loc='center left', fontsize=6, ncol=1,
              handlelength=1.0, labelspacing=0.3,
              handletextpad=0.4)
    ax.grid(alpha=0.3, which='both')
    add_panel_label(ax, '(a)', x=0.015, y=0.99,
                    fontweight='normal', pad=0.8)

    # (b) per-level LWC envelope
    ax = axes[0, 1]
    p_in = np.percentile(lwc_common, pct, axis=0)
    p_sy = np.percentile(diag_lwc,   pct, axis=0)
    ax.fill_betweenx(u, p_in[0], p_in[2], alpha=0.30,
                     color=color_in, label='In-situ 5–95%')
    ax.plot(p_in[1], u, color=color_in, linewidth=1.5,
            label='In-situ median')
    ax.fill_betweenx(u, p_sy[0], p_sy[2], alpha=0.25,
                     color=color_syn, label='Synthetic 5–95%')
    ax.plot(p_sy[1], u, color=color_syn, linewidth=1.5,
            label='Synthetic median')
    ax.set_xscale('log')
    ax.set_xlabel(r'LWC (g/m$^3$, log)')
    ax.set_ylabel('Normalized altitude')
    ax.set_title('Per-level LWC envelope')
    ax.legend(loc='center left', fontsize=6, ncol=1,
              handlelength=1.0, labelspacing=0.3,
              handletextpad=0.4)
    ax.grid(alpha=0.3, which='both')
    add_panel_label(ax, '(b)', x=0.015, y=0.99,
                    fontweight='normal', pad=0.8)

    # (c) cloud thickness distribution
    ax = axes[0, 2]
    bins = np.linspace(min(in_thickness.min(), syn_thickness.min()),
                       max(in_thickness.max(), syn_thickness.max()), 40)
    ax.hist(in_thickness,  bins=bins, density=True, alpha=0.55,
            color=color_in,  label='In-situ')
    ax.hist(syn_thickness, bins=bins, density=True, alpha=0.55,
            color=color_syn, label='Synthetic')
    ax.set_xlabel('Cloud thickness (km)')
    ax.set_ylabel('Density')
    ax.set_title('Cloud thickness')
    ax.legend(fontsize=7)
    ax.grid(alpha=0.3)
    add_panel_label(ax, '(c)', x=0.015, y=0.99,
                    fontweight='normal', pad=0.8)

    # (d) tau_c
    ax = axes[1, 0]
    bins = np.logspace(np.log10(min(in_tau_c.min(), syn_tau_c.min())),
                       np.log10(max(in_tau_c.max(), syn_tau_c.max())), 50)
    ax.hist(in_tau_c,  bins=bins, density=True, alpha=0.55,
            color=color_in,  label='In-situ')
    ax.hist(syn_tau_c, bins=bins, density=True, alpha=0.55,
            color=color_syn, label='Synthetic')
    ax.set_xscale('log')
    ax.set_xlabel(r'$\tau_c$')
    ax.set_ylabel('Density')
    ax.set_title(r'Cloud optical depth $\tau_c$')
    ax.legend(fontsize=7)
    ax.grid(alpha=0.3, which='both')
    add_panel_label(ax, '(d)', x=0.015, y=0.99,
                    fontweight='normal', pad=0.8)

    # (e) LWP
    ax = axes[1, 1]
    bins = np.logspace(np.log10(max(min(in_lwp.min(), syn_lwp.min()), 1e-3)),
                       np.log10(max(in_lwp.max(), syn_lwp.max())), 50)
    ax.hist(in_lwp,  bins=bins, density=True, alpha=0.55,
            color=color_in,  label='In-situ')
    ax.hist(syn_lwp, bins=bins, density=True, alpha=0.55,
            color=color_syn, label='Synthetic')
    ax.set_xscale('log')
    ax.set_xlabel(r'LWP (g/m$^2$)')
    ax.set_ylabel('Density')
    ax.set_title('Liquid water path')
    ax.legend(fontsize=7)
    ax.grid(alpha=0.3, which='both')
    add_panel_label(ax, '(e)', x=0.015, y=0.99,
                    fontweight='normal', pad=0.8)

    # (f) mean alpha — labeled with the libRadtran-alpha to gamma-distribution
    # effective-variance conversion, nu_eff = 1 / (alpha + 3).
    ax = axes[1, 2]
    bins = np.linspace(min(in_alpha.min(), syn_alpha.min()),
                       max(in_alpha.max(), syn_alpha.max()), 40)
    ax.hist(in_alpha,  bins=bins, density=True, alpha=0.55,
            color=color_in,  label='In-situ')
    ax.hist(syn_alpha, bins=bins, density=True, alpha=0.55,
            color=color_syn, label='Synthetic')
    ax.set_xlabel(r'Vertical-mean $\alpha$  '
                  r'($\nu_{\mathrm{eff}} = 1/(\alpha + 3)$)')
    # The xlabel is longer than the 2.33"-wide panel; shift it leftward so
    # the right parenthesis is not clipped against the panel right edge.
    ax.xaxis.set_label_coords(0.42, -0.16)
    ax.set_ylabel('Density')
    ax.set_title(r'Mean $\alpha$')
    ax.legend(fontsize=7)
    ax.grid(alpha=0.3)
    add_panel_label(ax, '(f)', x=0.015, y=0.99,
                    fontweight='normal', pad=0.8)

    return fig


def main():
    setup_style()
    d = np.load(NPZ_PATH)

    # PCA-mode figures (3x1 single-column)
    for option in (1, 2, 3):
        fig = make_pca_modes_figure(d, option)
        out_path = OUT_DIR / (
            f'synthetic_profiles_jointMVN_pca_modes_3x1_N300001_'
            f'opt{option}_{OPTION_TAG[option]}.png'
        )
        fig.savefig(out_path, dpi=FIGURE_DPI, bbox_inches='tight')
        plt.close(fig)
        print(f'pca-modes opt{option} ({OPTION_TAG[option]}) -> {out_path}')

    # 2x3 comparison figure (in-situ vs synthetic)
    try:
        in_situ = load_in_situ(L_common=int(d['L_COMMON']))
    except FileNotFoundError as e:
        print(f'WARNING: skipping comparison figure: {e}')
        return

    fig = make_comparison_figure(d, in_situ)
    out_path = OUT_DIR / 'synthetic_profiles_jointMVN_comparison_2x3_N300001.png'
    fig.savefig(out_path, dpi=FIGURE_DPI, bbox_inches='tight')
    plt.close(fig)
    print(f'comparison -> {out_path}')


if __name__ == '__main__':
    main()
